apiVersion: v1
kind: Service
metadata:
  name: my-java-app-lb
  namespace: default
  labels:
    app.kubernetes.io/name: my-java-app-lb
spec:
  type: LoadBalancer
  selector:
    app: my-java-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP