apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-lb
  namespace: default
  labels:
    app.kubernetes.io/name: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: phpmyadmin
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP